<?php

namespace ZohoSubscriptions\Requests;

use MacsiDigital\API\Support\PersistResource;

class StoreSubscription extends PersistResource
{
    protected $persistAttributes = [
        'id' => '',
        'customer.display_name' => 'required_without:customer_id|string',
        'customer.email' => 'required_without:customer_id|string',
        'customer.salutation' => 'nullable|string',
        'customer.first_name' => 'nullable|string',
        'customer.last_name' => 'nullable|string',
        'customer.tags' => 'nullable|array',
        'customer.company_name' => 'nullable|string',
        'customer.phone' => 'nullable|string',
        'customer.mobile' => 'nullable|string',
        'customer.department' => 'nullable|string',
        'customer.designation' => 'nullable|string',
        'customer.website' => 'nullable|string',
        'customer.billing_address.attention' => 'nullable|string',
        'customer.billing_address.street' => 'nullable|string',
        'customer.billing_address.city' => 'nullable|string',
        'customer.billing_address.state' => 'nullable|string',
        'customer.billing_address.zip' => 'nullable|string',
        'customer.billing_address.country' => 'nullable|string',
        'customer.billing_address.state_code' => 'nullable|string',
        'customer.billing_address.fax' => 'nullable|string',
        'customer.shipping_address.attention' => 'nullable|string',
        'customer.shipping_address.street' => 'nullable|string',
        'customer.shipping_address.city' => 'nullable|string',
        'customer.shipping_address.state' => 'nullable|string',
        'customer.shipping_address.zip' => 'nullable|string',
        'customer.shipping_address.country' => 'nullable|string',
        'customer.shipping_address.state_code' => 'nullable|string',
        'customer.shipping_address.fax' => 'nullable|string',
        'customer.payment_terms' => 'nullable|integer',
        'customer.payment_terms_label' => 'nullable|string',
        'customer.currency_code' => 'nullable|string',
        'customer.ach_supported' => 'nullable|bool',
        'customer.twitter' => 'nullable|string',
        'customer.facebook' => 'nullable|string',
        'customer.skype' => 'nullable|string',
        'customer.notes' => 'nullable|string',
        'customer.is_portal_enabled' => 'nullable|bool',
        'customer.gst_no' => 'nullable|string',
        'customer.gst_treatment' => 'nullable|string',
        'customer.place_of_contact' => 'nullable|string',
        'customer.vat_treatment' => 'nullable|string',
        'customer.tax_reg_no' => 'nullable|string',
        'customer.tds_tax_id' => 'nullable|string',
        'customer.tax_treatment' => 'nullable|string',
        'customer.tax_regime' => 'nullable|string',
        'customer.tax_id' => 'nullable|string',
        'customer.tax_authority_id' => 'nullable|string',
        'customer.tax_authority_name' => 'nullable|string',
        'customer.tax_exemption_id' => 'nullable|string',
        'customer.tax_exemption_code' => 'nullable|string',
        'customer.is_tds_registered' => 'nullable|bool',
        'customer.vat_reg_no' => 'nullable|string',
        'customer.is_taxable' => 'nullable|bool',
        'customer.default_templates.invoice_template_id' => 'sometimes|required|string',
        'customer.default_templates.creditnote_template_id' => 'sometimes|required|string',
        'customer.custom_fields.*.label' => 'sometimes|required|string',
        'customer.custom_fields.*.value' => 'sometimes|required|string',
        'customer_id' => 'required_without:customer|string',
        'payment_terms' => 'nullable|integer',
        'payment_terms_label' => 'nullable|string',
        'custom_fields' => 'nullable|array',
        'card_id' => 'nullable|string',
        'starts_at' => 'nullable|string',
        'exchange_rate' => 'nullable|integer',
        'place_of_supply' => 'nullable|string',
        'plan.plan_code' => 'required|string',
        'plan.plan_description' => 'nullable|string',
        'plan.price' => 'nullable|integer',
        'plan.trial_days' => 'nullable|integer',
        'plan.setup_fee' => 'nullable|integer',
        'plan.setup_fee_tax_id' => 'nullable|string',
        'plan.tags.*.tag_id' => 'sometimes|integer',
        'plan.item_custom_fields.*.label' => 'sometimes|required|string',
        'plan.item_custom_fields.*.value' => 'sometimes|required|string',
        'plan.quantity' => 'nullable|integer',
        'plan.tax_id' => 'nullable|string',
        'addons' => 'nullable|array',
        'coupon_code' => 'nullable|string',
        'auto_collect' => 'nullable|bool',
        'reference_id' => 'nullable|string',
        'salesperson_name' => 'nullable|string',
        'payment_gateways.*.payment_gateway' => 'sometimes|required|string',
        'create_backdated_invoice' => 'nullable|bool',
        'can_charge_setup_fee_immediately' => 'nullable|bool',
        'template_id' => 'nullable|string',
        'cfdi_usage' => 'nullable|string',
        'allow_partial_payments' => 'nullable|bool',
    ];
}
